platinumVideos/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path
from platvids import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    #AUTH URLS
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    #PlatinumCollections
    path('platinumcollection/create', views.Create_Collection.as_view(), name='create_collection'),
    #For CRUD
    path('platinumcollection/<int:pk>', views.Detail_Collection.as_view(), name='detail_collection'),
    path('platinumcollection/<int:pk>/update', views.Update_Collection.as_view(), name='update_collection'),
    path('platinumcollection/<int:pk>/delete', views.Delete_Collection.as_view(), name='delete_collection'),
    #Videos
    path('platinumcollection/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

platvids/models.py
from django.db import models
from django.contrib.auth.models import User

class Platvid(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    platvid = models.ForeignKey(Platvid, on_delete=models.CASCADE)

platvids/forms.py
from .models import Video
from django import forms

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url':'YouTube Url'}


class SearchForm(forms.Form):
    search_query = forms.CharField(max_length=255, label = 'Search Video')

platvids/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import  authenticate, login
from .models import Platvid, Video
from .forms import VideoForm, SearchForm
from django.http import Http404, JsonResponse
import urllib
import requests
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


YouTube_API_Key = 'AIzaSyCXfghmwef9j7sEMt1Km-N6VsuC-CJW0k0'


def index(request):
    recent_platvids = Platvid.objects.all().order_by('-id')[:3]
    popular_platvids = [Platvid.objects.get(pk=1),Platvid.objects.get(pk=2),Platvid.objects.get(pk=3)]
    return render(request, 'platvids/index.html', {'recent_platvids':recent_platvids, 'popular_platvids': popular_platvids})

@login_required
def dashboard(request):
    platvids = Platvid.objects.filter(user=request.user)
    return render(request, 'platvids/dashboard.html', {'platvids':platvids})

@login_required
def add_video(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    platvid = Platvid.objects.get(pk=pk)
    if not platvid.user == request.user:
        raise Http404

    if request.method=='POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.platvid = platvid
            video.url = form.cleaned_data['url']
        
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={ YouTube_API_Key }')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title  = title
                video.save()
                return redirect('detail_collection', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a valid YouTube URL')

    return render(request, 'platvids/add_video.html', {'form':form, 'search_form': search_form, 'platvid':platvid})

@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_query'])
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={ encoded_search_term }&key={ YouTube_API_Key }')
        return JsonResponse(response.json())
    return JsonResponse({'error': 'Not able to validate submitted form.'})

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

#auto login after signup
    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


#function based view would be hedious to create here! i used class based view instead..
class Create_Collection(LoginRequiredMixin, generic.CreateView):
    model = Platvid
    fields = ['title']
    template_name = 'platvids/create_collection.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(Create_Collection, self).form_valid(form)
        return redirect('dashboard')


class Detail_Collection(generic.DetailView):
    model = Platvid
    template_name = 'platvids/detail_collection.html'


class Update_Collection(LoginRequiredMixin, generic.UpdateView):
    model = Platvid
    template_name = 'platvids/update_collection.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        platvids = super(Update_Collection, self).get_object()
        if not platvids.user == self.request.user:
            raise Http404
        return platvids


class Delete_Collection(LoginRequiredMixin, generic.DeleteView):
    model = Platvid
    template_name = 'platvids/delete_collection.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        platvids = super(Delete_Collection, self).get_object()
        if not platvids.user == self.request.user:
            raise Http404
        return platvids


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'platvids/delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.platvid.user == self.request.user:
            raise Http404
        return video

platvids/templates/platvids/add_video.html
{% extends 'platvids/base.html' %}

{% block content %}

<div class="container">
    <h1>Add Video to {{ platvid.title }}</h1>
    <form method="post" id="submit_video">
        {% csrf_token %}
        {% load widget_tweaks %}

        {% for field in form %}
        <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
            {{ field.errors }}
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Add</button>
    </form>
    <br>
    <h2>OR</h2>
    <form>
        {% for field in search_form %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}
    </form>

    <div id="search_results"></div>
    <script>
        var delay;
        $('#id_search_query').keyup(function () {
            clearTimeout(delay);
            $('#search_results').text('Loading...');
            delay = setTimeout(function () {
                var text = $('#id_search_query').val();
                $.ajax({
                    url: '/video/search',
                    data: {
                        'search_query': text
                    },
                    dataType: 'json',
                    success: function (data) {

                        var results = '';
                        $('#search_results').text('');

                        results += '<div class="row">';
                        data['items'].forEach(function (video) {
                            results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                            results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] + '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                            results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
                            results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';


                        });
                        results += '</div>';

                        $('#search_results').append(results);
                    }
                });
            }, 1500);
        });

        function addVideo(video_id) {
            $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
            $('#submit_video').submit();
        }

    </script>

</div>

{% endblock %}

platvids/templates/platvids/base.html
<!doctype html>
<html lang="en">
{% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>platinum videos</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link href="{% static 'custom.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'index' %}" class="text-dark">PlatinunVideos</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
      {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
      {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
    <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
    {% endif %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  {% block content %}
  {% endblock %}
  
</body>

</html>

platvids/templates/platvids/create_collection.html
{% extends 'platvids/base.html' %}

{% block content %}

<div class="container">
<h1>Create platnumCollection</h1>
    <form method="post">
        {% csrf_token %}

        {% load widget_tweaks %}
        {% for field in form %}
        <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
            {{ field.errors }}
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

{% endblock %}

platvids/templates/platvids/dashboard.html
{% extends 'platvids/base.html' %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h2>{{ user.username }}'s platinumCollection</h2>
        <a href="{% url 'create_collection' %}" class="btn btn-primary">Create New platinumCollection</a>
    </div>

    {% for platvid in platvids %}

    <h3><a href="{% url 'detail_collection' platvid.id %}">{{ platvid.title }}</a></h3>
    <a href="{% url 'add_video' platvid.id %}" class="btn btn-primary">Add Video</a>
    <a href="{% url 'update_collection' platvid.id %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'delete_collection' platvid.id %}" class="btn btn-danger">Delete</a>

    <div class="row">
        {% for video in platvid.video_set.all %}

        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/'{{ video.youtube_id }}"
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

</div>
{% endblock %}

platvids/templates/platvids/delete_collection.html
{% extends 'platvids/base.html' %}

{% block content %}

<div class="container">
<h1>Are you sure you want to delete {{ platvid.title }}?</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

<br>
<h2><a href="{% url 'delete_collection' platvid.id %}">{{ platvid.title }}</a></h2>

</div>

{% endblock %}

platvids/templates/platvids/delete_video.html
{% extends 'platvids/base.html' %}

{% block content %}

<div class="container">
    <h1>Are you sure you want to delete this Video?</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

    <div class="row">
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">'
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/'{{ video.youtube_id }}"
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>
                </div>
            </div>
        </div>

    </div>

    {% endblock %}

platvids/templates/platvids/detail_collection.html
{% extends 'platvids/base.html' %}

{% block content %}
<div class="container">

<h2>{{ platvid.title }}</h2>
<h4 class='text-muted'>{{ platvid.user.username }}</h4>

{% if user.id == platvid.user.id %}
<a href="{% url 'add_video' platvid.id %}" class="btn btn-primary">Add Video</a>
<a href="{% url 'update_collection' platvid.id %}" class="btn btn-primary">Edit</a>
<a href="{% url 'delete_collection' platvid.id %}" class="btn btn-danger">Delete</a>
{% endif %}

<div class="row">
    {% for video in platvid.video_set.all %}

    <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">'
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/'{{ video.youtube_id }}"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
            <div class="card-body">
                <p class="card-text">{{ video.title }}</p>
                {% if user.id == platvid.user.id %}
                <a href="{% url 'delete_video' video.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

</div>
{% endblock %}

platvids/templates/platvids/index.html
{% extends 'platvids/base.html' %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class='jumbotron-heading'>
            Want to make your personal platinumCollection?
        </h1>
        <p class="lead text-muted">
            Put all those YouTube videos you've always wanted the world to see into your own, custom-made
            platinumCollection! Get Started Below..
        </p>
        <p class="btn btn-primary">
            Make your platinumCollection
        </p>
    </div>
</section>

<div class="container">
    <h1 class="text-center">Popular Additions</h1>
    {% for platvid in popular_platvids %}
    <h2><a href="{% url 'detail_collection' platvid.id %}">{{ platvid.title }}</a></h2>
    <div class="row">
        {% for video in platvid.video_set.all %}

        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/'{{ video.youtube_id }}"
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

    <h1 class="text-center">Recent Additions</h1>
    {% for platvid in recent_platvids %}
    <h2><a href="{% url 'detail_collection' platvid.id %}">{{ platvid.title }}</a></h2>
    <div class="row">
        {% for video in platvid.video_set.all %}

        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/'{{ video.youtube_id }}"
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

</div>
{% endblock %}

platvids/templates/platvids/update_collection.html
{% extends 'platvids/base.html' %}

{% block content %}

<div class="container">
<h1>Edit platnumCollection</h1>
    <form method="post">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}
        <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
            {{ field.errors }}
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
<br>
<a href="{% url 'delete_collection' platvid.id %}" class="btn btn-danger">Delete platnumCollection</a>

</div>

{% endblock %}